- lib/praxis/tasks/api_docs.rb
- lib/praxis/tasks/console.rb
Add a description so people know the task exists. Make pry and irb use Praxis::Application.instance as the 'self' object.
> Improve praxis:console task.

- CHANGELOG.md
- lib/praxis/api_definition.rb
- lib/praxis/responses/http.rb
- lib/praxis/responses/internal_server_error.rb
- lib/praxis/responses/validation_error.rb
> Add descriptions to the default http responses.

- CHANGELOG.md
- lib/praxis/action_definition.rb
- lib/praxis/media_type.rb
- lib/praxis/resource_definition.rb
- lib/praxis/restful_doc_generator.rb
- spec/praxis/action_definition_spec.rb
- spec/praxis/media_type_spec.rb
- spec/praxis/resource_definition_spec.rb
Now with 100% fewer bugs and MediaType support.
> Add nodoc to resources and actions

- reference/resource-definitions.md
> Add docs for nodoc

- CHANGELOG.md
- lib/praxis/tasks/routes.rb
- praxis.gemspec
> Replace Ruport with TerminalTable for routes rake task.

- CHANGELOG.md
- lib/praxis/bootloader_stages/environment.rb
- lib/praxis/router.rb
- spec/praxis/router_spec.rb
> Add configurable X-Cascade header support.

- CHANGELOG.md
- lib/praxis/controller.rb
- lib/praxis/request_stages/request_stage.rb
- lib/praxis/request_stages/response.rb
- lib/praxis/stage.rb
- spec/praxis/request_stage_spec.rb
> Tighten up RequestStage shortcutting with responses.

- tasks/thor/example.rb
1. Every file was indented by two spaces; this broke the magic comment at the top of `config.ru`. (And just looked odd.)
2. `rackup` should be run through `bundle exec`, and doesn't need the port when the magic comment is working. (The port argument is actually ignored if the magic comment is there; see https://github.com/rack/rack/pull/798).
3. Typo fix commented -> commenced.
> Fix example app generator

- lib/praxis/restful_doc_generator.rb
Fixes #120.
Signed-off-by: Michelle Sausa <michelle@rightscale.com>
> Fix non-default media type documentation generation.

- lib/api_browser/app/views/controller.html
- lib/praxis/controller.rb
- lib/praxis/resource_definition.rb
- lib/praxis/restful_doc_generator.rb
- lib/praxis/simple_media_type.rb
> Rework generated filenames for documentation.

- _config.yml
- reference/api-definition.md
- reference/global-api-information.md
> Document global api information

- reference/controllers.md
- reference/resource-definitions.md
> Add documentation for canonical paths.

- reference/media-type-collections.md
- reference/media-types.md
> Document reworked collections.

- reference/doc-generation.md
> Docs changes related to #132

- lib/praxis/action_definition.rb
- lib/praxis/dispatcher.rb
- lib/praxis/request_stages/request_stage.rb
- lib/praxis/request_stages/validate_params_and_headers.rb
- lib/praxis/request_stages/validate_payload.rb
- spec/praxis/request_stage_spec.rb
* A small set of memory allocation improvements for the fast path of a request.
* Fixed request stages to not try to setup themselves for every incoming request.
> A few small improvements and fixes

- .gitattributes
- CHANGELOG.md
- lib/praxis/action_definition.rb
- spec/praxis/action_definition_spec.rb
> Add source information to params descriptions for actions.

- CHANGELOG.md
- lib/praxis/links.rb
- spec/praxis/media_type_spec.rb
- spec/support/spec_media_types.rb
> Fix generated Links accessors to load the returned value.

- CHANGELOG.md
- lib/praxis/restful_doc_generator.rb
- lib/praxis/types/multipart.rb
- praxis.gemspec
- spec/praxis/types/multipart_spec.rb
* Fixed doc generation code for custom types
* Hardened Multipart type loading
Fixes #167
> Fix generation of docs for Multipart payloads

- CHANGELOG.md
- tasks/thor/example.rb
Spruced up the example app (generator) to use the latest `prefix` and `trait` changes
> Update example generated app

- .rspec
- CHANGELOG.md
- lib/praxis.rb
- lib/praxis/action_definition.rb
- lib/praxis/api_definition.rb
- lib/praxis/api_general_info.rb
- lib/praxis/application.rb
- lib/praxis/bootloader_stages/routing.rb
- lib/praxis/request.rb
- lib/praxis/resource_definition.rb
- lib/praxis/router.rb
- spec/functional_spec.rb
- spec/praxis/api_general_info_spec.rb
- spec/praxis/request_spec.rb
- spec/praxis/resource_definition_spec.rb
- spec/praxis/router_spec.rb
- spec/spec_app/design/api.rb
- spec/spec_app/design/resources/volumes.rb
- spec/spec_helper.rb
> Add support for specifying version options in global api information.

- reference/global-api-information.md
- reference/requests.md
- reference/resource-definitions.md
> Improve docs for versioning options, and add new path-based support.

- lib/api_browser/app/js/factories/template_for.js
- spec/api_browser/directives/type_placeholder_spec.js
- spec/api_browser/factories/template_for_spec.js
This caused action params to not render.
> Fixes issue with wrong type family rendering

- CHANGELOG.md
- lib/praxis/api_general_info.rb
- spec/praxis/api_general_info_spec.rb
> Add 'endpoint' directive to global api info.

- reference/global-api-information.md
> Document 'endpoint' global api information directive.

- lib/praxis/response_definition.rb
- spec/praxis/response_definition_spec.rb
> Add rendered examples to ResponseDefinition#describe

- reference/resource-definitions.md
> Document parent directive.

- reference/application.md
> Added docs for the new Application.validation_handler customization.

- lib/praxis/multipart/part.rb
- lib/praxis/types/multipart_array.rb
- spec/praxis/types/multipart_array_spec.rb
> Add proper describe output for MultipartArray.

- lib/praxis/types/multipart_array.rb
- spec/praxis/types/multipart_array_spec.rb
> Fix MultipartArray.payload_type not accepting a block to further define the type

- _config.yml
- reference/handlers.md
- reference/multipart.md
- reference/resource-definitions.md
> Begin documenting new multipart support.

- reference/global-api-information.md
> Add new produces/consumes metadata to global api information.

- lib/praxis/action_definition.rb
- lib/praxis/restful_doc_generator.rb
> Minor fixes to doc generation for MultipartArray types.

- lib/praxis/router.rb
- spec/functional_spec.rb
- spec/praxis/router_spec.rb
@blanquer fixed 'speficied' typo
> fix_speficied_typo

- CHANGELOG.md
- lib/praxis/application.rb
- lib/praxis/dispatcher.rb
- lib/praxis/request_stages/action.rb
- lib/praxis/request_stages/request_stage.rb
- spec/praxis/request_stages/action_spec.rb
- spec/spec_app/design/media_types/volume.rb
> Add additional instrumentation hooks.

- README.md
When a run generate command I've got the follow message:
This is a deprecated method.
To generate a hello world example, please use:
praxis example my-app 
Would you please accept it?
> update README.md generate example

- README.md
- praxis.gemspec
- spec/spec_helper.rb
This runs code coverage tests and sends the results to Coveralls. 
This also adds Coveralls and Gemnasium badges.
> Run code coverage stats. Add coverage and gemnasium gems

- lib/api_browser/app/js/app.js
- lib/api_browser/app/js/factories/template_for.js
- lib/api_browser/app/views/builtin/field-selector.html
- lib/api_browser/app/views/types/embedded/field-selector.html
- lib/praxis/extensions/field_selection/field_selector.rb
This is based on the proposed curly brace syntax.
> Adds docs for FieldSelectors

- reference/plugins.md
- reference/plugins/plugins_framework.md
> Adds docs for doc browser plugins

- lib/api_browser/app/js/directives/request_examples.js
- lib/api_browser/app/js/directives/url.js
@blanquer this fixes the example showing instead of the url.
> Fixes example showing in generic url directive

- praxis.gemspec
- spec/praxis/plugins/praxis_mapper_plugin_spec.rb
- spec/praxis/response_definition_spec.rb
- spec/praxis/response_spec.rb
- spec/spec_app/config/environment.rb
Note: If you try to run the tests under Jruby, there are a couple of then that are failing for multipart_part (due to some Tempfile type issue that still needs to be investigated)...
> Tweaks and examples on how to use JDBC in Jruby in the spec_app

- CHANGELOG.md
- lib/praxis/trait.rb
- spec/praxis/trait_spec.rb
Signed-off-by: Josep M. Blanquer <blanquer@gmail.com>
> Additive blocks for Traits’ params/headers/payload

- getting-started.md
Signed-off-by: Josep M. Blanquer <blanquer@gmail.com>
> Change doc generation cmd line examples to the non-deprecated syntax

- CONTRIBUTING.md
- lib/api_browser/package.json
- praxis.gemspec
- tasks/thor/templates/generator/empty_app/Gemfile
https://github.com/praxis/praxis/issues/323
> Update generator template

- .travis.yml
- lib/praxis/action_definition.rb
- lib/praxis/action_definition/headers_dsl_compiler.rb
- lib/praxis/application.rb
- lib/praxis/config.rb
- lib/praxis/media_type_identifier.rb
- lib/praxis/notifications.rb
- lib/praxis/resource_definition.rb
- lib/praxis/route.rb
- lib/praxis/routing_config.rb
- lib/praxis/trait.rb
- lib/praxis/types/media_type_common.rb
- lib/praxis/types/multipart.rb
- lib/praxis/types/multipart_array.rb
- lib/praxis/types/multipart_array/part_definition.rb
- praxis.gemspec
- spec/praxis/action_definition_spec.rb
- spec/praxis/application_spec.rb
- spec/praxis/collection_spec.rb
- spec/praxis/config_spec.rb
- spec/praxis/media_type_spec.rb
- spec/praxis/middleware_app_spec.rb
- spec/praxis/request_stages/action_spec.rb
- spec/praxis/response_definition_spec.rb
- spec/praxis/response_spec.rb
- spec/praxis/router_spec.rb
- spec/spec_app/app/controllers/instances.rb
still has a dependent gitted attributor gem hardcoded
> Ruby2.7 steps

- CHANGELOG.md
- lib/praxis/blueprint.rb
- lib/praxis/collection.rb
- lib/praxis/docs/open_api/media_type_object.rb
- lib/praxis/docs/open_api/operation_object.rb
- lib/praxis/docs/open_api/schema_object.rb
- lib/praxis/docs/open_api/tag_object.rb
- lib/praxis/docs/open_api_generator.rb
- lib/praxis/tasks/api_docs.rb
- praxis.gemspec
ported OpenApi fixes and enhancements to denormalize components use $ref when appropriate
> Open API fixes, and usage of references

- lib/praxis/docs/open_api/schema_object.rb
This change seeks to correct the Open API metadata by correcting the assignment and value of the `"required"` trait on payload parameters.
A notable deficiency is the inability to represent `.at_most(x) | .at_least(x) | .exactly(x)` requirements, as there aren't default fields for denoting that level of logic.
> Assign Correct Nullability to Payload Types

- Gemfile
- lib/praxis/action_definition/headers_dsl_compiler.rb
- lib/praxis/blueprint.rb
- lib/praxis/blueprint_attribute_group.rb
- lib/praxis/extensions/pagination/pagination_params.rb
- lib/praxis/media_type_identifier.rb
- lib/praxis/types/multipart_array.rb
- spec/praxis/blueprint_spec.rb
- spec/spec_app/design/media_types/book.rb
- spec/support/spec_blueprints.rb
* Bump to new Attributor gem
* Cleaned up AttributeGroup target vs. reference
* Full matrix of specs for type inheritance and :reference for blueprints
> Attribute inheritance
