- CHANGELOG.md
- CONTRIBUTING.md
- lib/api_browser/app/js/controllers/menu.js
Previously reloading the doc browser wouldn't preserve the right hand menu's state:
This PR fixes that so that the menu reflects the version in the URL.
> Reloading doesn't reset the right hand menu anymore

- CHANGELOG.md
- lib/praxis/route.rb
Before we would see this for actions:
This PR should fix it so that only the string part of the URL is shown as expected.
> Makes doc browser show proper links

- getting-started.md
As `praxis generate` is now a deprecated command, the documentation should be updated to give the new command instead.
> Modified 'praxis generate' to 'praxis example' in docs

- CHANGELOG.md
- lib/api_browser/app/js/directives/attribute_table_row.js
- lib/api_browser/app/views/action.html
- lib/api_browser/app/views/directives/attribute_table.html
- lib/api_browser/app/views/directives/attribute_table_row/_default.html
- lib/api_browser/app/views/directives/attribute_table_row/_links.html
- lib/api_browser/app/views/directives/attribute_table_row/_struct.html
- lib/api_browser/app/views/directives/request_body/_default.html
- lib/api_browser/app/views/resource/_actions.html
The doc browser was using divs to display tables. This is highly inaccessible (good luck with a screen reader) and breaks in the following ways:
1. Columns overlap:
2. Breaks completely on mobile:
This PR changes all of these to use proper tables. To solve these issues.
> Uses proper tables for tabular data

- lib/praxis/plugins/praxis_mapper_plugin.rb
When creating a Praxis::Mapper::IdentityMap using setup! it is possible to receive a previously created identity map that has already had finalize! called on it, resulting in the below error:
```#<RuntimeError: Denied for a pre-existing condition: Identity map has been used.>```
Using new creates a new IdentityMap every time and is generally safer.
Signed-off-by: Justin Gaylor <justin.gaylor@gmail.com>
> Use 'new' instead of 'setup!' for safety

- CHANGELOG.md
- lib/praxis/action_definition.rb
- lib/praxis/media_type.rb
- lib/praxis/media_type_collection.rb
- lib/praxis/resource_definition.rb
- lib/praxis/restful_doc_generator.rb
- praxis.gemspec
- spec/praxis/action_definition_spec.rb
- spec/praxis/media_type_spec.rb
- spec/praxis/resource_definition_spec.rb
This updates a new doc_visibility option to the value of :nodoc, which is used
by the RestfulDocGenerator to skip generation for objects with it set.
Closes #74
> Add nodoc! to ActionDefinition, ResourceDefinition, and MediaType.

- CHANGELOG.md
- lib/api_browser/app/js/controllers/action.js
- lib/api_browser/app/js/controllers/type.js
Was caused by a boolean check instead of a nil check. Fixes similar potential issue in some other places.
> Fixes #97: default false not showing in docbrowser

- CHANGELOG.md
- lib/praxis/plugins/praxis_mapper_plugin.rb
- spec/praxis/plugins/praxis_mapper_plugin_spec.rb
* configurable log-level
* Can skip logs at the individual request level
* Short message when identity map has had interactions.
Fixes #107, fixes #108, fixes #109
> Enhanced several logging aspects of the PraxisMapper plugin

- CHANGELOG.md
- lib/praxis/router.rb
- lib/praxis/skeletor/restful_routing_config.rb
- spec/functional_spec.rb
- spec/praxis/restful_routing_config_spec.rb
- spec/praxis/router_spec.rb
- spec/spec_app/design/resources/instances.rb
To use it, employ the `any` DSL word when defining a route: 
```ruby
routing do
any '/things/:id’
end
```
> Added a handy option to tie an action route to match any HTTP verb

- CHANGELOG.md
- lib/praxis/action_definition.rb
- lib/praxis/controller.rb
- lib/praxis/request.rb
- lib/praxis/request_stages/request_stage.rb
- lib/praxis/resource_definition.rb
- spec/praxis/action_definition_spec.rb
- spec/praxis/resource_definition_spec.rb
- spec/spec_app/app/controllers/instances.rb
- spec/spec_app/design/resources/instances.rb
- spec/support/spec_resource_definitions.rb
Added the definition and handling of canonical urls for API resources
* One can now specify which action URL should be considered as the canonical resource href:
* by using `canonical_path <action_name>` at the top of the resource definition class
* See the [instances](https://github.com/rightscale/praxis/blob/master/spec/spec_app/design/resources/instances.rb) resource definition for an example.
* With a canonical href defined, one can then both generate and parse them by using:
* `.to_href(<named arguments hash>)  =>  <href String>`
* `.parse_href( <href String> )  => < named arguments hash >`. Note: The returned arguments are properly typed-coerced.
* These helpers can be accessed from:
* the `definition` object in the controller instance (i.e., `self.definition.to_href(id: 1). )
* or …
> Definition and handling of canonical urls for API resources

- CHANGELOG.md
- bin/praxis
In particular added: 
* praxis routes [json] 
* praxis docs [browser] 
* praxis console 
Also made both Thor generators and rake tasks to use a common usage message.
```
Commands:
praxis console            # Open a console to the application, with its environment loaded
praxis docs [browser]     # Generates API JSON documents. Automatically starts a Web bowser with 'browser' parameter
praxis example APP_NAME   # Generates a new 'hello world' example application under an <app_name> directory
praxis generate APP_NAME  # DEPRECATED!: Generates a new 'hello world' example application under an <app_name> directory
praxis help [COMMAND]     # Describe available commands or one specific command
praxis new APP_NAME       # Generates a blank new app under <app_name> (with a full skeleton ready to …
```
> Hooked up rake tasks into the `praxis` binary for convenience.

- CHANGELOG.md
- lib/praxis/bootloader.rb
- lib/praxis/resource_definition.rb
- lib/praxis/stage.rb
- spec/praxis/bootloader_spec.rb
- spec/praxis/stage_spec.rb
* `setup!` is no longer called within the `run` default code of a stage 
* removed unnecessary raise error when substages are empty (while not common it can be possible, and totally valid)
> Improved code for stages

- lib/praxis/tasks/api_docs.rb
Adds deprecation notices and cleans up upgrade path (so now if we changes the default layout of those files, they should be generated correctly).
We ran into this when upgrading to master, my colleagues tried running `rake praxis:doc_browser` and then complained that this praxis is broken.
> Doc browser rake cleanup

- CHANGELOG.md
- lib/api_browser/Gruntfile.js
- lib/praxis/tasks/api_docs.rb
* `rake praxis:docs:preview[4567]` will now launch the server on port 4567 (instead of the 9090 default)
> Enhances the praxis:docs:preview with an optional port parameter

- CHANGELOG.md
- lib/praxis/links.rb
- spec/praxis/media_type_spec.rb
- spec/support/spec_media_types.rb
> Improve type inheritance for `link` method with `:using` option.

- CHANGELOG.md
- lib/praxis/action_definition.rb
When action missing routing block, praxis:docs:generate would crash. Now generation continues
with warning message printed.
Signed-off-by: Michelle Sausa <michelle@rightscale.com>
> Add warning message for doc gen task. Fixes #151.

- CHANGELOG.md
- lib/praxis/types/media_type_common.rb
- spec/praxis/media_type_spec.rb
Fixed `MediaType#describe` to include the correct string representation of its identifier.
> 170 stack recursion rendering docs

- CHANGELOG.md
- lib/praxis/router.rb
- lib/praxis/routing_config.rb
- lib/praxis/tasks/routes.rb
- lib/praxis/types/media_type_common.rb
- spec/functional_spec.rb
- spec/praxis/media_type_spec.rb
- spec/praxis/router_spec.rb
- spec/praxis/routing_config_spec.rb
- spec/spec_app/app/controllers/instances.rb
- spec/spec_app/design/resources/instances.rb
Allow route options to be passed to the underlying router (i.e. Mustermann at the moment)
* routes defined in the `routing` blocks can now take any extra options which will be passed down to the Mustermann routing engine. Unknown options will be ignored!
* Displaying routes (`praxis routes` or `rake praxis:routes`) will now include any options defined in a route.
* Added an example on the instances resource of the embedded spec_app to show how to use the advanced `*` pattern and the `:except` Mustermann options (along with the required `:splat` attribute).
closes #166
> Allow native routing options

- lib/api_browser/Gruntfile.js
This means you can now have images and other custom files in your docs folder and these will end up unmodified in `docs/output` when running `rake praxis:docs:build`.
> Build copies unrecognised files into output

- CHANGELOG.md
- lib/praxis/bootloader_stages/subgroup_loader.rb
- spec/spec_app/config/environment.rb
* Fix bug where before/after hooks set on sub-stages of `:app` would not be triggered
closes #179 
> Bootloader hooks for sub-stages are not called

- CHANGELOG.md
- lib/praxis/request.rb
- lib/praxis/request_stages/response.rb
- lib/praxis/request_stages/validate.rb
- lib/praxis/request_stages/validate_params_and_headers.rb
- lib/praxis/request_stages/validate_payload.rb
- lib/praxis/responses/validation_error.rb
- spec/functional_spec.rb
- spec/praxis/responses/validation_error_spec.rb
* Changed `message` for `summary`. Always present, and should provide a quick description of the type of error encountered. For example: "Error loading payload data"
* Semantically changed `errors` to always have the details of one or many errors that have occurred. For example: "Unknown key received: :foobar while loading $.payload.user"
> Refactored `ValidationError` body for consistency

- CHANGELOG.md
- lib/api_browser/app/js/controllers/menu.js
- lib/api_browser/app/js/factories/Configuration.js
- lib/api_browser/app/sass/modules/_sidebar.scss
- lib/api_browser/app/views/home.html
- lib/api_browser/app/views/layout.html
- lib/api_browser/app/views/menu.html
- lib/api_browser/app/views/navbar.html
- lib/praxis/restful_doc_generator.rb
Currently the styling works only for one level of nesting.
This also adds a `ConfigurationProvider` service, that allows configuring some aspects of the doc browser. Namely if you don't like the fact that subresources are hidden by default, you can add this to your app.js:
```javascript
angular.module('DocBrowser', ['PraxisDocBrowser'])
.config(function(ConfigurationProvider) {
ConfigurationProvider.expandChildren = false;
});
```
> Adds expandable tree-like navigation for child resources

- lib/praxis/resource_definition.rb
* Constructing the parent route in a nested resource could match partial symbols (and skip matching the last one too) depending on the names.
* The gsub regexp fixes those bugs.
> Fix parent route pattern substitution

- CHANGELOG.md
- lib/api_browser/app/js/factories/template_for.js
- lib/api_browser/app/views/menu.html
The issue for the builds was that some custom DI was not protected from overly aggressive minification.
@careo I think this should be released ASAP, as the build functionality is used in production.
This closes #220 and #218.
> Fixes Broken Build and version Selector

- lib/praxis/restful_doc_generator.rb
Needed to validate any attributes with the `required_if` option set.
Fixes #230
> Set Attributor::AttributeResolver.current in RestfulDocGenerator.new

- lib/praxis/types/multipart_array.rb
- spec/praxis/types/multipart_array_spec.rb
This includes minor interface breakage: MultipartArray.payload_type can no longer be used as an accessor. (MultipartArray#payload_type still works though)
It would be possible to restore this functionality by checking if there are no args or blocks, but this seems unnecessary. =/
> MultipartArray payload_type defaults to Attributor::Struct.

- CHANGELOG.md
- lib/praxis/action_definition.rb
- spec/praxis/action_definition_spec.rb
- spec/spec_app/design/resources/instances.rb
This is probably what most people expect from it, so let's make it so.
To make any of those three definitions non-required, simply add the `:required` option as used in any other attribute definition. For example: 
```
payload required: false do 
attribute :foobar, String
end
```
>  Make action headers, params and payloads be required by default

- lib/api_browser/app/js/controllers/type.js
- lib/api_browser/app/views/controller.html
- lib/api_browser/app/views/type/details.html
- lib/praxis/simple_media_type.rb
- spec/praxis/response_definition_spec.rb
Fixed displaying of the default schema for a controller in the Doc Browser:
* Changed SimpleMediaType to be described in the same format of any other MediaType
* Changed doc browser to expect a hash defining the default media_type of a controller (containing a family and the identifier) amongst other.
* Added a simple display of the Schema that just shows an internet media_type identifier when the default one for the controller is a SimpleMediaType (i.e. string type)
> Controller Schema for a Controller missing:

- lib/praxis/types/multipart_array.rb
- spec/praxis/types/multipart_array_spec.rb
Defining a part using the `file` syntax and passing in the `type` for it, it would still default to a `String` type.
> Fix bug in MultipartArray file

- CHANGELOG.md
- lib/praxis/media_type_identifier.rb
- spec/praxis/media_type_identifier_spec.rb
> Handle loading empty MediaTypeIdentifier values:

- lib/praxis/collection.rb
- spec/praxis/types/collection_spec.rb
- spec/support/spec_media_types.rb
Ensure the media-type identifier is always properly set
to the member’s identifier + “type=collection” regardless
of creating the collection using `.of` or through `.member_type` 
Fixes #244 
> Praxis::Collection.member_type sets the identifier

- lib/praxis/action_definition.rb
- lib/praxis/restful_doc_generator.rb
* Removed unnecessary lines in the doc generator (that assumed a default media_type for a resource had attributes)
* Allow passing in the nil reference for params/payload in an action (to override the default media_type one)
Fixes #243 
> Allow DocBrowser to accept collections as default media types

- CHANGELOG.md
- lib/praxis/docs/generator.rb
* Make generator to skip reporting versions in index for which we have no resources (after applying the nodoc! directive)
> Handle versions with all resources `nodoc!’d`

- CHANGELOG.md
- lib/praxis/docs/generator.rb
This could happen for Mts that existed but that
there were never referenced in any other part of the app.
Fixes #273
> Fixes potential missing schemas from doc gen

- CHANGELOG.md
- lib/api_browser/Gruntfile.js
- lib/api_browser/app/index.html
- lib/api_browser/app/js/directives/highlight.js
- lib/api_browser/app/js/directives/request_examples.js
- lib/api_browser/app/js/factories/Documentation.js
- lib/api_browser/app/js/factories/Example.js
- lib/api_browser/app/js/factories/prepare_template.js
- lib/api_browser/app/js/factories/template_for.js
- lib/api_browser/app/views/action.html
- lib/api_browser/app/views/examples/general.html
- lib/api_browser/bower_template.json
This PR adds an API that users/plugins can hook into to generate code examples for the doc browser. These can either be specific hand written ones, or they can be generic functions that simply generate the appropriate code. This [gist](https://gist.github.com/gampleman/672bc02860694d90aa5d) shows an example of a code generator.
> Code examples

- lib/praxis/api_definition.rb
- lib/praxis/docs/generator.rb
- lib/praxis/simple_media_type.rb
* Doc generation: handle SimpleMediaTypes so that they don’t show up in the generated schemas. Fixes #283
* ensure we require AS#Enumerable extension is loaded, which is required in the generator code.
* Add Date to the list of primitive types so that it does not show in the generated schemas.
* enhaneg the `:created` response_template, so that it can take the associated media_type
> Assorted fixes:

- reference/resource-definitions.md
Describe payload inheritance in the resource-definitions section (we only had mentions in the getting started guide).
> Document payload inheritance

- lib/api_browser/app/views/controller.html
Use the appropriate `display_name` string in the heading of the resource page (like we do for the nav bar)
@gampleman can you please review and merge if appropriate?
> Fix name in Doc browser's controller heading

- CHANGELOG.md
- lib/praxis/docs/generator.rb
Enhanced doc generator to make sure it detects all reachable types.
Some types might have not been  properly reported in the `schemas` section of the JSON docs if they were only used somewhere  deep in some other type or action hierarchy
> 296 fix scanning of types for doc generation

- lib/praxis/extensions/field_expansion.rb
- spec/praxis/extensions/field_expansion_spec.rb
Make sure the field expansion extension still works for actions where no parameters are defined (in which cases expands to the default view)
fixes #300
> Field expansion supports no-parameter actions

- lib/api_browser/app/js/filters/attribute_name.js
Properly gray the prefix of attribute names in a table when there are more than 2 nested hashes/structs.
> Correct graying of attribute names in deep nesting

- CHANGELOG.md
- lib/praxis/bootloader.rb
- spec/praxis/bootloader_spec.rb
Allow Plugins to default their config_key appropriately based on class name.
fixes #131 
> Default config_key for Plugins

- CHANGELOG.md
- lib/praxis/action_definition.rb
- lib/praxis/resource_definition.rb
- spec/praxis/action_definition_spec.rb
- spec/praxis/resource_definition_spec.rb
Trigger Resources to "inherit" any of the defined `base_params` in the APIDefinition, both global ones as well as the ones defined for the same version of the resource. Inheritance is done through incorporating them into `action_defaults` so that any action defined in the resource will automatically copy them as usual.
That is instead of the special-casing of attribute merging done at the time of “params” definition for an action. That would occasionally blow up since it is not delayed and some reference MediaTypes would not have been finalized yet.
Fixes #308
Signed-off-by: Josep M. Blanquer <blanquer@gmail.com>
> Resources inherit APIDefinition `base_params` properly and lazily.

- CHANGELOG.md
- lib/praxis.rb
- lib/praxis/middleware_app.rb
- spec/praxis/middleware_app_spec.rb
* Build a helper to mount a Praxis application as an intercepting middleware which would handle requests, and only forward requests that cannot be properly handled by it (respecting X-Cascade).
> Helper for Praxis as an intercepting Middleware

- lib/praxis.rb
- lib/praxis/dispatcher.rb
- lib/praxis/extensions/rails_compat.rb
- lib/praxis/extensions/rails_compat/request_methods.rb
- lib/praxis/plugins/rails_plugin.rb
- lib/praxis/request.rb
- lib/praxis/request_superclassing.rb
- lib/praxis/response.rb
- spec/praxis/responses/internal_server_error_spec.rb
- spec/praxis/responses/validation_error_spec.rb
* Refactored dispatcher methods so that instrumentation can be easily added on (but without building a flexible hook system that might decrease the performance)
* Change `Praxis:Request` so that it can be made to derive from a base class (by default derives from Object)
* Build `rails_compat` extension. Which for now only:
* changes `Praxis:Request` to derive from `ActionDispatch::Request`
* Will load the RailsPlugin code
* Build a `RailsPlugin` plugin which, for now, will:
* emulate firing off the `action_controller` basic hooks (`start_processing` and `process_action`).
* Add a few basic controller methods (which make some of the other mixing you might want to throw in your controllers happier).
* TODO: db and view runtime values on request processing not done (i.e., not integrated with …
> Build initial Rails embeddability/compat:

- CHANGELOG.md
- praxis.gemspec
The new series might be required by some of the newer gems which might be pulled in by Rails 5 and such.
Default pattern for mustermann continues being Sinatra, which has some new features but it is backwards compatible.
Signed-off-by: Josep M. Blanquer <blanquer@gmail.com>
> Allow for the new mustermann 1.x series

- .travis.yml
- CHANGELOG.md
- README.md
- lib/api_browser/app/js/directives/attribute_table.js
- lib/api_browser/app/js/directives/conditional_requirements.js
- lib/api_browser/app/js/directives/type_placeholder.js
- lib/api_browser/app/js/factories/normalize_attributes.js
- lib/api_browser/app/js/factories/template_for.js
- lib/api_browser/app/js/filters/has_requirement.js
- lib/api_browser/app/js/filters/tag_requirement.js
- lib/api_browser/app/sass/praxis.scss
- lib/api_browser/app/views/action.html
- lib/api_browser/app/views/directives/attribute_description/member_options.html
- lib/api_browser/app/views/directives/attribute_table.html
- lib/api_browser/app/views/type.html
- lib/api_browser/app/views/type/details.html
- lib/api_browser/app/views/types/embedded/array.html
- lib/api_browser/app/views/types/embedded/default.html
- lib/api_browser/app/views/types/embedded/requirements.html
- lib/api_browser/app/views/types/embedded/single_req.html
- lib/api_browser/app/views/types/embedded/struct.html
- lib/api_browser/app/views/types/standalone/array.html
- lib/api_browser/app/views/types/standalone/struct.html
- lib/praxis/middleware_app.rb
- spec/praxis/middleware_app_spec.rb
* proper showing of substructures of payloads when arrays
* mark required attributess with red star (and semi-required as orange)
* display the existing special requirements as well
* added requirements for parameters as well (in addition to payload)
* format member_options display better
I'm sure not the "proper" angular way in some ways, but this is actually broken for APIs that have collections of structs, and more importantly: until now, the conditional requirements were never shown in the browser.
> Fix and improve Doc Browser presentation:

- CHANGELOG.md
- lib/praxis/extensions/field_selection/active_record_query_selector.rb
- lib/praxis/extensions/field_selection/sequel_query_selector.rb
- lib/praxis/mapper/active_model_compat.rb
- lib/praxis/mapper/resource.rb
- lib/praxis/mapper/selector_generator.rb
- lib/praxis/mapper/sequel_compat.rb
- lib/praxis/plugins/mapper_plugin.rb
- praxis.gemspec
- spec/praxis/extensions/field_selection/active_record_query_selector_spec.rb
- spec/praxis/extensions/field_selection/sequel_query_selector_spec.rb
- spec/praxis/extensions/field_selection/support/spec_resources_active_model.rb
- spec/praxis/extensions/field_selection/support/spec_resources_sequel.rb
- spec/praxis/mapper/selector_generator_spec.rb
- spec/spec_app/app/models/person.rb
- spec/spec_helper.rb
- spec/support/be_deep_equal_matcher.rb
- spec/support/spec_resources.rb
Reworked the field selection DB query generation to support full tree of eager loaded dependencies (rather than normalizing it all at the top-level models).
- Built support for both ActiveRecord and Sequel gems (and added actual models and in-memory Sqlite DB tests)
- The selected DB fields will include/map the defined resource properties and will always include any necessary fields on both sides of the joins for the given associations.
- Added a configurable option to enable debugging of those generated queries (through `Praxis::Application.instance.config.mapper.debug_queries=true`)
> Full support for Tree-based generated field-selection queries

- CHANGELOG.md
- lib/praxis/extensions/attribute_filtering/filtering_params.rb
- lib/praxis/extensions/attribute_filtering/filters_parser.rb
- spec/praxis/extensions/attribute_filtering/filtering_params_spec.rb
- spec/praxis/extensions/attribute_filtering/filters_parser_spec.rb
* Before the fix, the whole filters string was decoded, where only the values should
* when multi-value filters used, only the individual values must be encoded/decoded as well, not the separating commas
> fix the decoding of value filters

- bin/praxis
- lib/praxis/extensions/attribute_filtering/active_record_filter_query_builder.rb
avoids adding a `.references` call to the query being constructed for our filters, ONLY WHEN the condition is for our root table (need to add the other references for any joined tables to get the aliases right).
Adding the root table as a reference wil make AR to eager load it all, as it does not match that reference name to any of the already joined tables, and therefore will think the query needs to eager load them all, as the condition will be referencing some of them...
> Fix eager loading for root where clauses

- CHANGELOG.md
- lib/praxis/extensions/attribute_filtering/active_record_filter_query_builder.rb
- lib/praxis/version.rb
- spec/praxis/extensions/attribute_filtering/active_record_filter_query_builder_spec.rb
- spec/praxis/extensions/support/spec_resources_active_model.rb
- spec/spec_helper.rb
Switch filters to use left outer joins with an extra condition for the joined row (this fixes certain incorrect combination of association conditions with ORs, where inner joins would have discarded valid rows to apply where clauses)
Built in existence (and non-existence) of associated rows in filters using the same ! and !! operators
> Filters fixes and improvements

- CHANGELOG.md
- lib/praxis/extensions/attribute_filtering/filtering_params.rb
- spec/praxis/extensions/attribute_filtering/filtering_params_spec.rb
added the `any` DSL for a filter, to specify that it would allow filters that end with that attribute name (regardless of them being nested)
This allows an easier way to glob attributes for filtering, that can be represented by the same type and operator. i.e., filter by any updated_at attribute of any reachable mediatype
> Added `any` DSL for filters

- CHANGELOG.md
- lib/praxis/extensions/attribute_filtering/active_record_filter_query_builder.rb
- spec/praxis/extensions/attribute_filtering/active_record_filter_query_builder_spec.rb
- spec/praxis/extensions/support/spec_resources_active_model.rb
- tasks/thor/templates/generator/example_app/app/v1/resources/user.rb
- tasks/thor/templates/generator/scaffold/implementation/resources/item.rb
allow same-path filters to be allowed in `filters_mapping` without having to explicitly list them
> Implicit filters_mapping entries for existing column and association paths

- CHANGELOG.md
- lib/praxis/mapper/resource.rb
- spec/praxis/mapper/resource_spec.rb
Introduced a method to reload a Resource (.reload), which will clear the memoized values and call record.reload as well
> Resource .reload and memoization fixes

- lib/praxis/docs/open_api/media_type_object.rb
Works well with my complex production API; it finds a bunch of formerly hidden types. We continue to lack test coverage for schema generation, but we can defer that 'till we decide to refactor it.
> Propose fix for OpenAPI schema dump of anonymous-wrapped non-anonymous types

- Gemfile
- lib/praxis/action_definition.rb
- lib/praxis/bootloader_stages/routing.rb
- lib/praxis/dispatcher.rb
- lib/praxis/docs/open_api/schema_object.rb
- lib/praxis/endpoint_definition.rb
- lib/praxis/request.rb
- lib/praxis/tasks/routes.rb
- praxis.gemspec
- spec/praxis/action_definition_spec.rb
- spec/praxis/endpoint_definition_spec.rb
- spec/support/spec_endpoint_definitions.rb
This PR introduces a new action dsl `enable_large_params_proxy_action` for GET verb actions.
When used two things will happen:
* A new POST verb equivalent action will be defined:
* It will have a `payload` matching the shape of the original GET's `params` (with the exception of any param that was originally in the URL):
* By default, the route for this new POST request is gonna have the same URL as the original GET action, but appending `/actions/<action_name>` to it. This can be customized by passing the path with the `at:` parameter of the DSL. I.e., `enable_large_params_proxy_action at: /actions/myspecialname` will change the generated path (can use the `//..` syntax to not include the prefix defined for the endpoint). NOTE: this route needs to be compatible with any params that might …
> Support for large parameters in GET requests (through a sister proxied POST action)

- Gemfile
- lib/praxis/docs/open_api/schema_object.rb
- lib/praxis/handlers/json.rb
- lib/praxis/mapper/active_model_compat.rb
- spec/functional_spec.rb
* Cache praxis associations' computation for ActiveRecord (so no communication with AR or DB happens after that)
* Use OJ as the (faster) default JSON renderer. Could make it configurable later on.
> Perf improvements

- lib/praxis/mapper/resource.rb
- spec/praxis/mapper/resource_spec.rb
- spec/support/spec_resources.rb
Optional DSL to enable easier calculation of expensive attributes that can be calculated much more efficiently in group:
* defining an attribute this way, resources can be used to be much more efficiently to calculate values that can be retrieved much more efficiently in bulk, and/or that depend on other resources of the same type to do so.
* The provided block to calculate the value of the attribute for a collection of resources of the same type is stored as a method inside an inner module of the resource class called BatchProcessors
* The class level method is callable through <ResourceClass>::BatchProcessors.<property_name>(rows_by_id: xxx). The rows_by_id: parameter has resource 'ids' as keys, and the resource instances themselves a values
* By default an instance method of the same …
> Build batch_computed DSL for resources

- lib/praxis/bootloader_stages/routing.rb
- lib/praxis/request.rb
- spec/functional_spec.rb
- spec/spec_app/design/resources/instances.rb
Revamp the switching of forwarded sister actions, for better handling of payloads
* We are now, explicitly marking a request as forwarding the action to the sister get one (rather than just knowing there was such a definition)
* Based on that, we're only gonna try to merge the params from the payload if such forwarding took place in the actual request
* This makes it clearer, more efficient, but especially disambiguates the fact that a normal GET request that tecnically has a sister post action might 'incorrectly' pass some content type with an empty payload, and we'd try to make sense out of that for param merging purposes (and possibly fail)
> Handle gets with content types and no bodies for proxied actions

- CHANGELOG.md
- lib/praxis/extensions/pagination/active_record_pagination_handler.rb
Change ordering code to no use `references` for a top level column name in sorting. If we do so, using quoted table name, AR will decide to eager load it all!
I've opened an issue about it: https://github.com/rails/rails/issues/47588
> Do not add a `.references` for root table names

- CHANGELOG.md
- lib/praxis/docs/open_api/operation_object.rb
- lib/praxis/docs/open_api/paths_object.rb
- lib/praxis/docs/open_api_generator.rb
Several improvements:
* Add global parameters for versioning (ApiVersionHeader and ApiVersionParam) appropriately if the API is versioned by them. Have actions point to these definitions by $ref
* Expect the 'server' definition in the APIDefinition to contain url/description and 'variables' sections which might define variables in the server url
> Improve open api generation

- lib/praxis/extensions/pagination/active_record_pagination_handler.rb
- spec/praxis/extensions/pagination/active_record_pagination_handler_spec.rb
Add a select for any order clause, as latest MySQL versions require it for DISTINCT queries
* Some of the latest MySQL does complain on an invalid query if you use an ORDER BY component that does not have the corresponding SELECT field. (I believe it is enforced, at least, when the query has a DISTINCT modifier)
> Support newer MySQL versions that require ordering fields to be in select clauses when using DISTINCT

- CHANGELOG.md
- gemfiles/active_6.gemfile.lock
- gemfiles/active_7.gemfile.lock
- lib/praxis.rb
- lib/praxis/application.rb
- lib/praxis/docs/open_api/schema_object.rb
- lib/praxis/extensions/field_expansion.rb
- lib/praxis/field_expander.rb
- lib/praxis/types/splattable_string_array.rb
- praxis.gemspec
- spec/functional_library_spec.rb
- spec/praxis/extensions/field_expansion_spec.rb
- spec/praxis/field_expander_spec.rb
- spec/spec_app/app/controllers/base_class.rb
- spec/spec_app/app/resources/book.rb
- spec/spec_app/design/media_types/book.rb
- spec/support/spec_blueprints.rb
This builds an easy way to control the hiding/displayability of MT attributes in requests
* It registers a :displayable custom attribute that can be used in any attribute, and accepts an array of opaque strings, which can represent some sort of 'privileges' required to have for it to be renderable.
* It allows to define a `display_attribute?` method in the controller, which takes a list of required 'privileges' coming from the attribute, and would return true/false to decide if that's a displayable (expandable) attribute (i.e., true if the 'current principal', whatever that means, has all of those privileges assigned).
* The expander tooling now, will use the `display_attribute?` method to decide if that needs to be expanded/displayed or not
This PR also changes the OpenAPI generation for …
> Field expansion with displayable

- CHANGELOG.md
- lib/praxis/blueprint.rb
- lib/praxis/docs/open_api/schema_object.rb
Looking at null: true | false to report nullability in OpenAPI isn't enough.
The system needs to look at the default null behavior from Attributor, to properly ascertain if the exclusion of a 'null' option means nullable or not. This PR fixes this.
> Abide by the default null behavior when reporting nullable to OpenAPI

- CHANGELOG.md
- gemfiles/active_6.gemfile.lock
- gemfiles/active_7.gemfile.lock
- lib/praxis/docs/open_api/schema_object.rb
check default_for_null to expose it as nullable if that's the default behavior, regardless of no null: key passed in in an attribute
> expose nullable: true when default_for_null is true

- CHANGELOG.md
- gemfiles/active_6.gemfile
- gemfiles/active_7.gemfile
- lib/praxis/handlers/json.rb
- spec/functional_cloud_spec.rb
- spec/spec_helper.rb
- tasks/thor/templates/generator/example_app/Gemfile
It has proven too difficult to work with `oj` in various situations:
- where Praxis is embedded into a Rails app
- where specs were written to use `JSON.dump` and `JSON.load` and assume that `Oj` works correspondingly
To facilitate upgrades, we're switching back to using `json` as the default JSON handler. Authors of Praxis apps can create their own `Oj` handlers as an optimization, if they're willing to deal with its idiosyncrasies.
> Revert to vanilla JSON handler

- gemfiles/.gitignore
- gemfiles/active_7.gemfile
- lib/praxis/tasks/console.rb
When we switched `praxis:console` back to using Irb, we adopted `multi-irb` because it was the easiest way to set the `main` binding to the Praxis app instance.
Unfortunately, `multi-irb` spawns a new thread for every instance of the interpreter. If the surrounding Praxis app needs to manipulate thread-local storage before entering the console, that capability is ruined and `multi-irb` provides no "hook" to allow us to execute code surrounding its invocation of the REPL.
Switching back to vanilla `irb` fixes the problem and makes our Irb integration slightly more robust against future major versions of the Ruby stdlib.
> Prevent IRB from running console in a new Thread

- lib/praxis/types/media_type_common.rb
was running into a weird error on attributor with a PR I'm going to put up soon, but basically if a collection of media types was nested within an Attributor::Hash, schema compilation would blow up with an argument length error for that hash object and not show up
> fix passing of kw args along to as_json_schema
